plugins {
    id 'org.springframework.boot' version '3.2.4' apply false
    id 'io.spring.dependency-management' version '1.1.4' apply false
}

tasks.named('wrapper') {
    gradleVersion = '8.6'
    distributionType = Wrapper.DistributionType.BIN
}

ext {
    set('springCloudVersion', "2023.0.1")
}

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    group = 'com.cyberlearnix.lms'
    version = '0.0.1-SNAPSHOT'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    repositories {
        mavenCentral()
    }
    
    test {
        useJUnitPlatform()
    }
}

