pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'cyber-lms-microservices'

include 'api-gateway'
include 'user-service'
include 'eureka-server'
include 'config-server'
include 'instructor-service'
include 'student_service'
include 'course-service'
include 'order-service'
include 'payment-service'
