server.port=8085
spring.application.name=order-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cyberlearnixdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cyberlearnix}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cyberlearnix123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=false

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=10000

user-service.url=${USER_SERVICE_URL:http://localhost:8081}
payment-service.url=${PAYMENT_SERVICE_URL:http://localhost:8086}
course-service.url=${COURSE_SERVICE_URL:http://localhost:8083}
