server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cyberlearnixdb}
    username: ${SPRING_DATASOURCE_USERNAME:cyberlearnix}
    password: ${SPRING_DATASOURCE_PASSWORD:cyberlearnix123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: cyberlearnixprivatelimited@gmail.com
    password: wxhqcbzyjfwhnoic
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

jwt:
  secret: CyberLearnixSuperSecureJWTKeyChangeThis
  expiration-ms: 3600000
  access-expiry-seconds: 3600

auth:
  lockout:
    max-attempts: 5
    duration-minutes: 15

token:
  expiry:
    hours: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG